const books = [
  {
    item_id: 'item1',
    title: 'The Great Gatsby',
    author: 'John Smith',
    category: 'Fiction',
  },
  {
    item_id: 'item2',
    title: 'Anna Karenina',
    author: 'Leo Tolstoy',
    category: 'Fiction',
  },
  {
    item_id: 'item3',
    title: 'The Selfish Gene',
    author: 'Richard Dawkins',
    category: 'Nonfiction',
  },
];

export const categories = [
  { name: 'Fiction' },
  { name: 'Non-fiction' },
  { name: 'Mystery' },
  { name: 'Thriller' },
  { name: 'Science Fiction' },
  { name: 'Fantasy' },
  { name: 'Romance' },
  { name: 'Historical Fiction' },
  { name: 'Horror' },
  { name: 'Adventure' },
  { name: 'Biography' },
  { name: 'Autobiography' },
  { name: 'Poetry' },
  { name: 'Drama' },
  { name: 'Comedy' },
  { name: 'Satire' },
  { name: 'Crime' },
  { name: 'Young Adult' },
  { name: "Children's" },
  { name: 'Self-help' },
  { name: 'Travel' },
  { name: 'Science' },
  { name: 'Philosophy' },
  { name: 'Religion' },
  { name: 'Art' },
  { name: 'Business' },
  { name: 'Psychology' },
  { name: 'Health and Wellness' },
  { name: 'Cookbooks' },
  { name: 'Sports' },
];
export default books;
