const books = [
  {
    id: 'item1',
    title: 'The Great Gatsby',
    author: 'John Smith',
    category: 'Fiction',
  },
  {
    id: 'item2',
    title: 'Anna Karenina',
    author: 'Leo Tolstoy',
    category: 'Fiction',
  },
  {
    id: 'item3',
    title: 'The Selfish Gene',
    author: 'Richard Dawkins',
    category: 'Nonfiction',
  },
];

export const categories = [
  'Category',
  'Fiction',
  'Non-fiction',
  'Mystery',
  'Thriller',
  'Science Fiction',
  'Fantasy',
  'Romance',
  'Historical Fiction',
  'Horror',
  'Adventure',
  'Biography',
  'Autobiography',
  'Poetry',
  'Drama',
  'Comedy',
  'Satire',
  'Crime',
  'Young Adult',
  "Children's",
  'Self-help',
  'Travel',
  'Science',
  'Philosophy',
  'Religion',
  'Art',
  'Business',
  'Psychology',
  'Health and Wellness',
  'Cookbooks',
  'Sports',
];
export default books;
